### ISSUE TITLE
get_or_create doesn't work

### ISSUE THREAD

**Issue by bauerj** [Python-Tools/aioorm#1]
```
2017-10-23 19:34:58 - (sanic)[ERROR]: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/sanic/app.py", line 503, in handle_request
    response = await response
  File "/home/bauerj/PycharmProjects/crashhub/lib/routes.py", line 25, in store_crash
    kind, created = await CrashKind.get_or_create(**crash["filter"])
  File "/usr/lib/python3.6/site-packages/aioorm/model.py", line 91, in get_or_create
    return await query.get(), False
  File "/usr/lib/python3.6/site-packages/aioorm/query.py", line 105, in get
    return await qr.__anext__()
  File "/usr/lib/python3.6/site-packages/aioorm/result.py", line 90, in __anext__
    obj = await self.iterate()
  File "/usr/lib/python3.6/site-packages/aioorm/result.py", line 71, in iterate
    raise StopAsyncIteration
StopAsyncIteration
```

Neither does `get`, as it seems.

**Comment by hsz1273327** [comment]
bug fixed in version 0.1.1~~~ thx for your report~
